### ISSUE TITLE
Question: Why not use `CamelCase` for class names?

### ISSUE THREAD

**Issue by hasansezertasan** [volfpeter/markyp-html#5]
Since many leading Python projects use the "CamelCase" naming convention for classes, why don't you use it?

Before checking the source code, I thought all the elements were functions but this convention led me to a misunderstanding, they are classes.

The decision-making for naming the elements might be affected by "HTML naming convention" but still, it's in Python.

**Comment by volfpeter** [comment]
This is an interesting question, because it only has subjective, opinionated answers :slightly_smiling_face:

Whatever HTML templating engine you use, you're fundamentally doing front-end development using HTML, CSS, and JS in a non-native environment (Python). Deviating from the naming convention of the native environment (HTML) would be a mistake in this case in my opinion, because the only reason to do so would be to highlight an implementation detail (the use of classes instead of functions), and also because it would only add friction to the development flow (your eyes and muscle memory knows `div` as `div`, not `Div`).

Notice that the "base" lib, `markyp` uses camel case class names, because in that scenario that is the correct choice. If I'd create custom higher order components from `markyp-html` elements, then I'd also recommend sticking to the Python naming convention. Well, sticking to the standard Python naming convention is almost always the correct choice, obviously...

I'd highlight that Python's standard library also often deviates from the standard naming convention, and for good reason. Even PEP8 offers flexibility: "Class names should **normally** use the CapWords convention".

**Comment by volfpeter** [comment]
> Note: I'm sorry if I sound arrogant, my English is not very good.

No worries, your English is very good and nothing felt arrogant :slightly_smiling_face: I'm happy to answer, it's nice to have a technical discussion!

> As a programmer, I would know that "things could be different" because I am in a "non-native environment".

Things should not be different! If they are different, then you need to adapt, do context switching if you work both with HTML or JSX and Python, which is likely and also objectively bad. With the current naming convention, your component hierarchy will look very very similar to what you'd write in React.

> As a programmer, I would probably know `Div` is related to an HTML tag called `div`...

I may have misunderstood what you meant, but it is a common misconception that server-side rendering (with a templating engine) is backend development and requires backend knowledge. If your Python code is producing HTML, you must have a decent understanding of HTML, CSS, and JS (well, as much as the complexity of the desired UI requires). So it can safely be assumed that whoever is using e.g. `markyp-html` is quite familiar with HTML already, in which case `div` will feel natural.

I'd note that frameworks like `relfex`, `nicegui`, `reactpy`, etc. also use the same convention as `markyp-html` (not that it validates my decision or anything, I think these frameworks didn't exist when I implemented this library).

**Comment by volfpeter** [comment]
@hasansezertasan After a long delay, I've finally had the time to finish and document my (way more advanced and async) `markyp-*` replacement, called `htmy` ([docs](https://volfpeter.github.io/htmy/)). I'm curious what you think about it, if you have some time to check it out (or even contribute an example like for `fasthx`).
